repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
  - repo: https://github.com/golangci/golangci-lint
    rev: v1.63.4
    hooks:
      - id: golangci-lint-full
        pass_filenames: true
        args: ["--enable=goimports,nilerr,prealloc,revive,unconvert,whitespace"]
      - id: golangci-lint-config-verify
